#! /usr/bin/env bash

package_name=casetools
first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"

export CASETOOLS_VERSION="$(
    find "${local_path}/${package_name}"-[.0-9]* -maxdepth 0 -mindepth 0 -type d -printf "%f\n" |
    awk -F- '{print $NF;}' |
    sort -nr |
    head -1
)"

lib_path="${local_path}/${package_name}-${CASETOOLS_VERSION}"

export CASETOOLS_SUBCOMMANDS="${lib_path}/subcommands"

. "${lib_path}/logging"
. "${lib_path}/exceptions"
. "${lib_path}/cases"
. "${lib_path}/paths"
. "${lib_path}/cloning"
. "${lib_path}/packaging"
. "${lib_path}/notebooks"
. "$(bashlib --lib)"

casetools::version() {
    echo "${CASETOOLS_VERSION}"
}

casetools::command_folder() {
    if [ -n "${CASETOOLS_SUBCOMMANDS}" -a -d "${CASETOOLS_SUBCOMMANDS}/." ]
    then
        echo "${CASETOOLS_SUBCOMMANDS}"
    fi
}

hash -r