#!/usr/bin/env bash

first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"

settings::attribute() {
    # <env var> <default value> [<set value>]
    #
    local _name _default_value="${2}" _supplied_value="${3}"

    if ! _name="${1:?Need to provide variable name}"
    then
        return $?
    elif [ -z "${!_name}" ]
    then
        export $_name="${_default_value}"
    fi

    if [ "${_supplied_value}" = "--reset" ]
    then
        export $_name="${_default_value}"
    elif [ -n "${_supplied_value}" ]
    then
        export $_name="${_supplied_value}"
    else
        logging::debug "env: ${_name}=${!_name}"
        echo "${!_name}"
    fi
}
