#!/usr/bin/env bash

#===================================================================================
#                          Import tools library
#===================================================================================
. "$(casetool --lib)"

#===================================================================================
#                              Logging Options
#===================================================================================
logging::set_severity info

follow_log() {
    tail -f $(cases::suites::get_log_file)
}

#===================================================================================
#                           Process command line options
#===================================================================================
optionslib::parse::description "Maintain Project services"

optionslib::parse::config "
    long_options=--help short_options=-h action=show_help description='Display instructions'
    long_options=--debug action=command name=logging::set_debug_severity description='Expose debug level logging'
    long_options=--info action=command name=logging::set_info_severity description='Expose normal level logging'
    long_options=--warning action=command name=logging::set_warning_severity description='Expose error level logging'
    long_options=--error action=command name=logging::set_error_severity description='Expose error level logging'
    long_options=--fatal action=command name=logging::set_fatal_severity description='Expose fatal error level logging'
    long_options=--lib action=command name=show_library_path description='Provide the library module import file'
    long_options=--version short_options=-v action=command name=casetools::version description='Produce the library version string'
    long_options=--list short_options=-l action=command name=cases::suites::get_installed_services description='List currently installed suite services'
    long_options=--update short_options=-u action=command name=cases::suites::update_project_services description='Maintain projects as suite services'
    long_options=--remove short_options=-r action=command name=cases::suites::remove_project_services description='Remove all managed suite services'
    long_options=--logfile action=command name=cases::suites::get_log_file description='Get service logfile path'
    long_options=--watch action=command name=follow_log description='Follow service log output'
"

optionslib::parse::parse_arguments "$@" || exit $?

