#! /usr/bin/env bash

first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"

. "${lib_path}/cases"

cases::folder::_exists() {
    if [ -e "${1:-'(no such file)'}" ]
    then
        echo "${1}"
        return
    fi

    false
}

cases::folder::tmp() {
    cases::folder::_exists "$(cases::selected)/Trash"
}

cases::folder::data() {
    cases::folder::_exists "$(cases::selected)/Data"
}

cases::folder::notes() {
    cases::folder::_exists "$(cases::selected)/Notes"
}

cases::folder::docs() {
    cases::folder::_exists "$(cases::selected)/Documentation"
}

cases::folder::tools() {
    cases::folder::_exists "$(cases::selected)/Tools"
}

cases::folder::icons() {
    cases::folder::_exists "$(casetools::share::path)/png"
}
